language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: V7VZkLM9A+p0vETkQDgYBrl99IpJaQmEfu7eo0r/cMtCZlBTZQ1AsskqcWDe9JXO1MOAkdox07PMPdHd6KE5zcdWgBFIj2kPuAoNI+8p39p8J9AhPCDrPwHEeOJiShgCUurEuaUJdSP2JVLAmewGCSw+spT5p+CySO7+KFDpkxbUu4W/GY1T6ffIiEdnnCkUTTI1DvEFXtmjPP2KOjfAuwfzjizPbx/GWCrG8BM9lfNsG600UE5VQfriBha4PwcwqGow1BvbseH/6JgL10f9iUb5jQ6rcZRRCVzHEJGCKZau05xH7YTrl0RhqMhJG8YaUDmPRiCzFD8iqa6EvmcKT5WhIjjBDte0tiVEGCSUPxX6HNk+RB2sBK0daGxzjCZtbi+X1cAkxilVAJSXOqmQKTiL0t7zxFhbZnIswxjP0kwRfMPBl3I2fOvn4D9t3IyXUkd/OQeyAJjmTBvFs1f2F31lpex5M/0ftE87HyfNHngf777v8S1lNoyfC6zbPj76v2pnzCHi7aAcOPu4v5LvXc9pDmLFxz2k0bVMZE5kLJ3spb8LaiUQDQmUnmtV7lL5GZFowzMwmVM0w56ieztFwW+oXG05phs0osbwWPEPZV38IFlgBjnUQZexR1XUr1CVSQj4bGzvY0soF+qq/MZK/F0CZj/C/6m4DZ0Hutpl6mY=
  app: limitless-dawn-73000
  on:
    repo: claytonweller/thinkful-blog-post
